feat: adding replaceServerVariablesWithValues function
asyncapi/generator-filters pull request #46
Opened 2021-08-01 11:39 UTC by amrutprabhu

**Description**
This is part of the pull request for adding Kafka broker settings. 
the `replaceServerVariablesWithValues` function is currently located in the nodejs-templae, but is also required in the spring-cloud-stream-template. 

@derberg had recommended moving this function to `generator-filters` as a common place for this common function. 

**Related issue(s)**
Helps to solve this PR: https://github.com/asyncapi/java-spring-cloud-stream-template/pull/125

2021-08-01 20:36 UTC, magicmatatjahu reviewed
@amrutprabhu Thanks for contribution! Could you also add the tests for new function in the `customFilters.test.js` file?

2021-08-01 20:36 UTC, magicmatatjahu commented on src/customFilters.js
> +
```suggestion
```

2021-08-02 13:54 UTC, derberg commented
@amrutprabhu lemme know if you need some help with tests, and also have a look at failing linter.

[here](https://github.com/asyncapi/generator-filters/blob/master/src/customFilters.test.js#L50) you can find an example of test with message model object, so you know how to do a test where [variable model](https://github.com/asyncapi/parser-js/blob/master/lib/models/server-variable.js) is involved

2021-08-07 17:21 UTC, amrutprabhu commented
@derberg I am new to javascript testing.. But I will try ..

2021-08-07 19:22 UTC, amrutprabhu commented
@derberg @magicmatatjahu Can you have a look at it.. ?

2021-08-09 09:22 UTC, derberg reviewed
It looks good, but improve tests as we should be consistent in there:

do this `const ServerVariable = require('@asyncapi/parser/lib/models/server-variable');`

then, instead of for example `const serverVariables = JSON.parse('{"port":{"_json":{"enum":["8080","8883"]}}}'); `

you should do `const serverVariables = new ServerVariable( { port: { enum: ["8080","8883"] } }); `

2021-08-09 10:06 UTC, magicmatatjahu requested changes
Tests fail. You should put JSON object (not stringified version) to the `ServerVariable` class.

2021-08-09 10:06 UTC, magicmatatjahu commented on src/customFilters.test.js
> +  const serverVariables = new ServerVariable( '{"port":{"default":"9092","enum":["8080","8883"]}}');
```suggestion
  const serverVariables = new ServerVariable({"port":{"default":"9092","enum":["8080","8883"]}}); 
```

2021-08-09 10:06 UTC, magicmatatjahu commented on src/customFilters.test.js
> +  const serverVariables = new ServerVariable( '{"port":{"enum":["8080","8883"]}}');
```suggestion
  const serverVariables = new ServerVariable({"port":{"enum":["8080","8883"]}}); 
```

2021-08-09 10:56 UTC, amrutprabhu commented
@derberg Apparently, the test fails after using the servervariables. How can I solve this? 
sorry for my lack of javascript knowledge.

2021-08-09 11:09 UTC, amrutprabhu commented
> @derberg Apparently, the test fails after using the servervariables. How can I solve this?
> sorry for my lack of javascript knowledge.

So I did a little debugging. Just printed the jsono format of the servervaraibels. And I get the following. 
```
{"_json":{"port":{"default":"9092","enum":["8080","8883"]}}}
```
Which apparently does not match what the function was expecting from https://github.com/asyncapi/nodejs-template/blob/fff91aa1f76db4682332f16bb91cdd78fb536ceb/template/config/common.yml#L41

2021-08-09 11:13 UTC, magicmatatjahu reviewed
Sorry 😅  You should pass variables as map/dictionary, not instance of ServerVariable class.

2021-08-09 11:13 UTC, magicmatatjahu commented on src/customFilters.test.js
> +  const serverVariables = new ServerVariable({port: { default:"9092", enum: ["8080","8883"]}});
```suggestion
  const serverVariables = { port: new ServerVariable({ default:"9092", enum: ["8080","8883"] }) }; 
```

2021-08-09 11:13 UTC, magicmatatjahu commented on src/customFilters.test.js
> +  const serverVariables = new ServerVariable({ port: { enum: ["8080","8883"] } });
```suggestion
  const serverVariables = { port: new ServerVariable({ enum: ["8080","8883"] }) }; 
```

2021-08-10 07:40 UTC, magicmatatjahu commented on src/customFilters.js
> +    const result = [], array;
`array` should be initialised as `let`.

2021-08-10 07:46 UTC, magicmatatjahu approved these changes
@amrutprabhu 👏🏼  Thanks for contribution!

2021-08-10 07:46 UTC, amrutprabhu commented
pheww.. Those were some long list of problems. :smile: 
Can you have a look now @derberg and @magicmatatjahu

2021-08-10 07:48 UTC, merged

2021-08-10 16:58 UTC, amrutprabhu commented
hey @magicmatatjahu,
I see that the docs that I had updated are not reflecting. 
It looks like the asyncapi-bot overrode my changes.

I see my change In the commit prior to it here: https://github.com/asyncapi/generator-filters/blob/f171ad4c3172f9446de26a2b80d2ffa0a40b4ff0/docs/api.md

2021-08-10 18:43 UTC, magicmatatjahu commented
@amrutprabhu Thanks for info! I will look at it, because it's very strange 🤔  PR with new docs should help :)

2021-08-11 07:46 UTC, derberg commented
@amrutprabhu I just noticed you updated API manually and not with `npm run docs`. @magicmatatjahu you looking into this or shall I?

2021-08-11 08:00 UTC, magicmatatjahu commented
I will, but I wanna understand why PR with bumped version removed the docs, if in pipeline we have appropriate script https://github.com/asyncapi/generator-filters/blob/c42fbe9f75860e055e9de4f80d892ec87ed26611/.github/workflows/if-nodejs-version-bump.yml#L31 🤔

2021-08-11 08:05 UTC, derberg commented
> but I wanna understand why PR with bumped version removed the docs

this is exactly why there were removed, cause `npm run docs` ran on version bump workflow. So the problem is somewhere with JSdoc imho, there must be some error that makes jsdoc2md to ignore it, thus remove if was added manually

2021-08-11 08:48 UTC, magicmatatjahu commented
PR -> https://github.com/asyncapi/generator-filters/pull/49